### PR TITLE
Dev to main

### PR DESCRIPTION
**Pull request by tahonen**

### CODE REVIEW

**Review by hanzala1234 — DISMISSED** [review]
LGTM

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-promotion:SNAPSHOT-PR-1-e4b11c3d` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-promotion:SNAPSHOT-PR-1-6b969cfe` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-promotion:SNAPSHOT-PR-1-dd96ff4e` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-promotion:SNAPSHOT-PR-1-acad8d58` is available

**Review by rasheedamir — DISMISSED** [review]

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-promotion:SNAPSHOT-PR-1-300c1ca9` is available

**Comment by hanzala1234** [comment]
dont merge now

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-promotion:SNAPSHOT-PR-1-02a5eca5` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-promotion:SNAPSHOT-PR-1-14e7163c` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-promotion:SNAPSHOT-PR-1-34738db4` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-promotion:SNAPSHOT-PR-1-37ddec70` is available

**Review by rasheedamir — DISMISSED** [review]

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-promotion:SNAPSHOT-PR-1-d7483572` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-promotion:SNAPSHOT-PR-1-b0b58c29` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-promotion:SNAPSHOT-PR-1-cf4d8642` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-promotion:SNAPSHOT-PR-1-1fd19db6` is available

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
